apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
    {
      "nodePathMap": [],
      "sharedFileSystemPath": [
        {
          "path": "/opt/taroko"
        }
      ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    absolutePath=${1}
    mkdir -m 0777 -p ${absolutePath}
  teardown: |-
    #!/bin/sh
    set -eu
    absolutePath=${1}
    rm -rf ${absolutePath}
