export TKIND="K8S"
export NTP="Internal"
export PROXY=""
export K8SCNI="canal"
[ "$KVER" ==  "" ] && export KVER='1.35.5' 

# Container Configuration
export NID="172.22.16.0/24"
export NGW="172.22.16.254"
export IMG="quay.io/cloudwalker/taroko:v${KVER}"
export LCTN="172.22.16.1:tklh-control-plane:6G:4 \
            172.22.16.2:tklh-worker1:8G:4 \
            172.22.16.3:tklh-worker2:8G:4"

# K8S Configuration
export SRVIP="172.22.16.1"
export KUBEVIP=""
export PNID="10.244.16.0/21"
export SNID="10.98.16.0/24"

# k8S Gateway Configuration
export TKGW="false"
export GWIF=""
export GWIP="172.20.5.200/16"
