apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: $SRVIP                   # change from Master node IP
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock         # change from CRI-O Unix Socket
  imagePullPolicy: IfNotPresent
  name: $cn-control-plane                                      # change from Master node hsotname
  taints: null
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
certificatesDir: /etc/kubernetes/pki
clusterName: $cn                             # set your clusterName
apiServer:
  extraArgs:
    - name: audit-log-format
      value: legacy        # text
    - name: audit-policy-file
      value: /opt/taroko/logs/apiserver/audit-policy.yaml
    - name: audit-log-path
      value: /opt/taroko/logs/apiserver/audit.log
    - name: audit-log-maxage
      value: "3"   # Retain logs for 3 days
    - name: audit-log-maxbackup
      value: "5"   # Retain 5 old log files
    - name: audit-log-maxsize
      value: "10"  # Rotate after 10MB
  extraVolumes:
    # Mount the Log Directory (Read-Write)
    # This allows the API server to write logs effectively to the host disk
    - name: audit-logs
      hostPath: /opt/taroko
      mountPath: /opt/taroko
      readOnly: false
      pathType: DirectoryOrCreate
    - name: host-localtime
      hostPath: /etc/localtime
      mountPath: /etc/localtime
      readOnly: true
      pathType: File
controllerManager:
  extraArgs:
    - name: node-cidr-mask-size              # set pod cidr per node
      value: "25"
    # Garbage Collection
    # Max number of terminated pods to keep before cleaning up
    - name: terminated-pod-gc-threshold
      value: "500"
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
      # Performance Tuning (Crucial for high latency networks)
      - name: heartbeat-interval
        value: "250"     # Default 100ms. Bump if network is jittery.
      - name: election-timeout
        value: "2500"      # Default 1000ms. 10x heartbeat is standard.
      # Snapshot/Storage
      - name: quota-backend-bytes
        value: "8589934592" # 8GB. Default is 2GB (often too small for prod).
      - name: auto-compaction-retention
        value: "3"    # Auto compact every 3 hour.
scheduler:
  extraArgs:
    # Security: Disable profiling to reduce attack surface
    - name: profiling
      value: "false"
    # Logging: Standard verbosity
    - name: v
      value: "2"
    # Networking: Ensure it binds only to localhost
    - name: bind-address
      value: "127.0.0.1"
dns: {}
imageRepository: registry.k8s.io
kubernetesVersion: $KVER
caCertificateValidityPeriod: 43800h0m0s      # 5 years
certificateValidityPeriod: 8760h0m0s         # 1 years
networking:
  dnsDomain: $cn.k8s                                    # DNS domain used by Kubernetes Services.
  podSubnet: ${PNID}                             # the subnet used by Pods.
  serviceSubnet: ${SNID}                           # subnet used by Kubernetes Services.
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: nftables
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
podPidsLimit: 8192
maxPods: 60
# podLogsDir: /opt/taroko/logs
imageMinimumGCAge: "2m0s"
imageMaximumGCAge: "168h"
containerLogMaxFiles: 3
containerLogMaxSize: 1Mi
shutdownGracePeriod: 60s
shutdownGracePeriodCriticalPods: 30s
#  GracefulNodeShutdown: true

#For example, if ShutdownGracePeriod=30s, and ShutdownGracePeriodCriticalPods=10s, 
#kubelet will delay the node shutdown by 30 seconds. During this time, 
#the first 20 seconds (30-10) would be reserved for gracefully terminating normal pods, 
#and the last 10 seconds would be reserved for terminating critical pods.

#evictionHard:
#  memory.available: "1024Mi"
#  nodefs.available: "10%"
#kubeReserved:
#  cpu: "500m"
#  memory: "1Gi"
#systemReserved:
#  cpu: "1"
#  memory: "1Gi"
#  ephemeral-storage: "10Gi"
