apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: $SRVIP                   # change from Master node IP
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock         # change from CRI-O Unix Socket
  imagePullPolicy: IfNotPresent
  name: ${cn}-control-plane                                      # change from Master node hsotname
  taints: null
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
certificatesDir: /etc/kubernetes/pki
clusterName: $cn                             # set your clusterName
apiServer: {}
controllerManager:
  extraArgs:
    - name: node-cidr-mask-size              # set pod cidr per node
      value: "25"
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kubernetesVersion: $KVER
caCertificateValidityPeriod: 43800h0m0s      # 5 years
certificateValidityPeriod: 8760h0m0s         # 1 years
networking:
  dnsDomain: $cn.k8s                                    # DNS domain used by Kubernetes Services.
  podSubnet: ${PNID}                             # the subnet used by Pods.
  serviceSubnet: ${SNID}                           # subnet used by Kubernetes Services.
scheduler: {}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: nftables
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
maxPods: 60
# podLogsDir: /opt/taroko/logs
containerLogMaxFiles: 3
containerLogMaxSize: 1Mi
shutdownGracePeriod: 60s
shutdownGracePeriodCriticalPods: 30s
#  GracefulNodeShutdown: true

#For example, if ShutdownGracePeriod=30s, and ShutdownGracePeriodCriticalPods=10s, 
#kubelet will delay the node shutdown by 30 seconds. During this time, 
#the first 20 seconds (30-10) would be reserved for gracefully terminating normal pods, 
#and the last 10 seconds would be reserved for terminating critical pods.

#evictionHard:
#  memory.available: "1024Mi"
#  nodefs.available: "10%"
#kubeReserved:
#  cpu: "500m"
#  memory: "1Gi"
#systemReserved:
#  cpu: "1"
#  memory: "1Gi"
#  ephemeral-storage: "10Gi"
