#!/usr/bin/env bash
source "$(dirname "$(realpath "$0")")/../../../lib/env.sh"

[ "$IP" == "" ] && echo "pls set IP variable" && exit 1
which ipvsadm &>/dev/null
[ "$?" != "0" ] && echo "pls install ipvsadm" && exit 1

# 條目對應教材（wulin）的 NodePort：tkadm ssh、prometheus/alertmanager/grafana
ipvs1="taroko:tkadm:22100:32200"
ipvs2="prom:dep-prometheus:9090:30090"
ipvs3="prom:alertmanager:3093:30093"
ipvs4="prom:grafana:3000:30030"

for iv in $ipvs1 $ipvs2 $ipvs3 $ipvs4
do
   ns=$(echo ${iv} | cut -d ':' -f1)
   npod=$(echo ${iv} | cut -d ':' -f2)
   hport=$(echo ${iv} | cut -d ':' -f3)
   nport=$(echo ${iv} | cut -d ':' -f4)
   # echo $ns,$npod,$hport,$nport; continue

   x=$(kubectl get pods -n "$ns" 2>/dev/null | grep "$npod" | cut -d ' ' -f1)
   if [ "$x" != "" ]; then
      sudo ipvsadm -Ln | grep $IP:$hport &>/dev/null
      [ "$?" == "0" ] && sudo ipvsadm -D -t $IP:$hport

      sudo ipvsadm -A -t $IP:$hport -s rr
      for n in $x
      do
        nip=$(kubectl exec $n -n $ns -- printenv HOST_IP)
        sudo ipvsadm -a -t $IP:$hport -r $nip:$nport -m
      done
   else
      sudo ipvsadm -Ln | grep $IP:$hport &>/dev/null
      [ "$?" == "0" ] && sudo ipvsadm -D -t $IP:$hport
   fi
done

sudo ipvsadm -Ln
