#!/usr/bin/env bash
source "$(dirname "$(realpath "$0")")/../../../lib/env.sh"

[ "$1" == "" ] && echo "kdg cluster" && exit 1

tk_load_conf $1 || exit 1

[ "$TKIND" != "K8S" ] && echo "$1 not K8S cluster" && exit 1
[ ! -d ${CLUSTERS_DIR}/$1 ] && echo "$1 cluster not found" && exit 1

sudo podman ps -a | grep " $1-worker2" | grep 'Exited ' &>/dev/null
[ "$?" == "0" ] && echo "$1-worker2 Exited" && exit 1

if [ "$TKGW" == "true" ]; then
   read -p "Are you sure ? " yn
   [ "$yn" != "YES" ] && exit 1

   # cif=${1}gw
   sudo podman exec -it ${1}-worker2 bash -c "ip a show tkgw" &>/dev/null
   if [ "$?" == "0" ]; then
      sudo podman exec -it ${1}-worker2 bash -c "ip link set dev tkgw down"
      sudo podman exec -it ${1}-worker2 bash -c "ip link delete tkgw"
      echo "$1-worker2 Gateway removed (tkgw:${GWIP})"
   else
      echo "$1-worker2 Gateway not found (tkgw:${GWIP})"
   fi
fi
