#!/usr/bin/env bash
source "$(dirname "$(realpath "$0")")/../../../lib/env.sh"

[ "$1" == "" ] && echo "krt cluster" && exit 1

[ ! -d ${CLUSTERS_DIR}/${1} ] && echo "$1 not exist" && exit 1

sudo podman ps -a | grep " $1" | grep 'Exited ' &>/dev/null
[ "$?" == "0" ] && echo "$1 already Exited" && exit 1

tk_load_conf ${1} || exit 1

for x in tkadm:taroko dtadm:dt
do
  lb=${x%%:*}
  ns=${x##*:}

  pn=$(kubectl get pod -l app=${lb} -o jsonpath="{.items[0].metadata.name}" -n $ns 2>/dev/null)
  if [ "$pn" != "" ]; then
     kubectl exec $pn -n $ns -- cp -p ${NODE_TAROKO_DIR}/${lb}bak/etc/passwd /etc/passwd
     kubectl exec $pn -n $ns -- cp -p ${NODE_TAROKO_DIR}/${lb}bak/etc/group /etc/group
     kubectl exec $pn -n $ns -- cp -p ${NODE_TAROKO_DIR}/${lb}bak/etc/shadow /etc/shadow
     [ "$?" == "0" ] && echo "$lb /etc restore ok"
     kubectl exec $pn -n $ns -- bash -c "unzip -o ${NODE_TAROKO_DIR}/${lb}bak/${lb}.zip -d / &>/dev/null"
     [ "$?" == "0" ] && echo "$lb /home restore ok"
  fi  
done
