#!/bin/bash
cd ~

sw=$(swapon --show)
[ "$sw" != "" ] && echo "pls turn off swapfile(/etc/fstab)" && exit 1

read -p "Are you sure ? " yn
[ "$yn" != "YES" ] && exit 1

# install cni
rm -r ${CNI_DIR} &>/dev/null
mkdir -p ${CNI_DIR}
curl -sL "$(curl -sL https://api.github.com/repos/containernetworking/plugins/releases/latest | \
jq -r '.assets[].browser_download_url' | grep 'linux-amd64.*.tgz$')" -o /tmp/cni-plugins.tgz &>/dev/null
tar xf /tmp/cni-plugins.tgz -C ${CNI_DIR}; rm /tmp/cni-plugins.tgz
echo "${CNI_DIR} ok"

# install kubectl
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &>/dev/null
chmod +x kubectl; sudo mv kubectl /usr/local/bin/
echo "kubectl ok"

# build taroko images
for n in 1.32.2 1.29.14 1.26.15
do
  sudo podman rmi quay.io/cloudwalker/taroko:v${n} &>/dev/null
  sudo podman build --build-arg VER=${n} --no-cache --force-rm -t quay.io/cloudwalker/taroko:v${n} \
  ${TK_HOME}/wulin/images/taroko/ &>/dev/null
  [ "$?" == "0" ] && echo "quay.io/cloudwalker/taroko:v${n} ok"
done 
