ARG VER=0.0
FROM alpine:${VER}
COPY ash.rc /usr/bin/

# minio client：建置時自官方釘版下載（原 COPY 的二進位不再進版控）
ARG MC_RELEASE=RELEASE.2025-08-13T08-35-41Z
ADD https://dl.min.io/client/mc/release/linux-amd64/archive/mc.${MC_RELEASE} /usr/bin/mc

RUN apk update && apk upgrade && apk add --no-cache nano sudo wget curl python3 py3-pip mysql-client git \ 
    openssh-client-default nfs-utils go sshpass tree bash shadow procps bind-tools util-linux coreutils \
    binutils findutils grep tzdata libcap jq yq zip unzip fuse shellcheck iptables iperf3 stress-ng \
    postgresql-client s3fs-fuse mailcap && \

    chmod +x /usr/bin/mc && \
    touch /usr/bin/ash.init /usr/bin/ash.service /usr/bin/ash.start && \
    passwd -dl root && \

    cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime && \

    # s3fs-fuse 與 mailcap 由 3.22 標準倉庫提供
    # （原自 edge 安裝的作法已失效：edge 的 s3fs-fuse 需要新版 libfuse3）
    echo 'user_allow_other' >> /etc/fuse.conf
    
    # install JuiceFS Client
    # curl -sSL https://d.juicefs.com/install | sh -

ENV ENV=/usr/bin/ash.rc

#CMD ["/bin/ash"]
CMD ["/bin/sleep","infinity"]
