apiVersion: v1
kind: Pod
metadata:
  name: base-gvisor
spec:
  runtimeClassName: gvisor
  containers:
  - name: base
    image: quay.io/cloudwalker/alp.base
  nodeSelector:
    kubernetes.io/hostname : c30-control-plane
